[project]
name = "EmailBuddy"
version = "1.0.0"
description = "Jac client application: EmailBuddy"
entry-point = "main.jac"

[dependencies]
numpy = ">=0.0.0"
sqlite-vec = ">=0.0.0"
byllm = ">=0.0.0"
sentence_transformers = ">=0.0.0"
huggingface-hub = ">=0.0.0"

[dependencies.npm]
jac-client-node = "1.0.3"
"@chatscope/chat-ui-kit-react" = "latest"
"@chatscope/chat-ui-kit-styles" = "latest"
antd = "latest"
"@ant-design/icons" = "latest"
vite = "latest"
"@vitejs/plugin-react" = "latest"

[dependencies.npm.dev]
"@jac-client/dev-deps" = "1.0.0"

[dev-dependencies]
watchdog = ">=3.0.0"

[serve]
base_route_app = "app"

[plugins.client]
